apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-in-file
  labels:
    app: api-in-file
    appvariant: filebased
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-in-file
      appvariant: filebased
  template:
    metadata:
      labels:
        app: api-in-file
        appvariant: filebased
    spec:
      volumes:
        - name: in-file-storage
          persistentVolumeClaim:
            claimName: infilepvc
      containers:
        - name: api-in-file
          image: sgdpro/sample-app:in-file
          env:
            - name: STORAGE_PATH
              value: "/usr/src/data/books-storage.json"
          ports:
            - containerPort: 3080
          volumeMounts:
            - mountPath: "/usr/src/data"
              name: in-file-storage
